### ISSUE TITLE
[Question] Why do we need to convert lux sensor measure?

### ISSUE THREAD

**Issue by pando85** [bruvv/LILYGO-T-Higrow-Esphome#22]
Hey, thanks for this great repository.

I would like to understand why we should add this code in bh1750:
```yaml
    # convert to illuminance
    filters:
      - lambda: |-
          return x * 200.0;
```
Thanks!
