### ISSUE TITLE
Extending the sensors while using the bruvv github repo

### ISSUE THREAD

**Issue by pascalfleury** [bruvv/LILYGO-T-Higrow-Esphome#37]
Documentation on https://bruvv.github.io/LILYGO-T-Higrow-Esphome/ tells me how to edit the file to do calibration and configuration for my version of the sensor (BME380, battery and no pump).

Besides forking the repo and adding my own modifications, is there a way to do the overriding in the esp yaml config on my home assistant directly? So I would get the latest version from the original source while keeping my changes.

More specifically: 
 - can I override things specified in the `packages` section ?
 - how can I delete a property or modify it (delete `accuracy_decimals` or `filters` and modify `unit_of_measurement`)

I think a sample such config would help tremendously, and I would volunteer some time to write a page about that.

**Comment by bruvv** [comment]
You’re right: overriding parts of an ESPHome package from a GitHub repo can be a bit tricky, but you can definitely keep using the original github:// reference and inject your own overrides locally. Here’s a clean way to do that without forking:

Example: Overriding Config While Using GitHub Package
```yaml
substitutions:
  name: my-higrow
  # Add custom values for calibration or disable sensors via conditional substitution
  moisture_min: "400"
  moisture_max: "2500"

packages:
  base: github://bruvv/LILYGO-T-Higrow-Esphome/LILYGO-T-Higrow-ESP32.yaml@main

esphome:
  name: ${name}

# Inject additional customizations here
sensor:
  - platform: template
    name: "Calibrated Moisture %"
    lambda: |-
      return (id(soil_moisture_raw).state - ${moisture_min}) * 100.0 / 
             (${moisture_max} - ${moisture_min});
    unit_of_measurement: "%"
    accuracy_decimals: 1
    update_interval: 60s
    id: soil_moisture_calibrated
    icon: "mdi:water-percent"

# Leave your WiFi/API/etc here as normal
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_key
```

Tips:
The substitutions section can be used to define custom values that are picked up inside the remote YAML if it's written to support it (you could expand support in your base YAML).

You can append extra sensor: or output: blocks after the packages: they won’t overwrite the original ones, but they'll be merged.

If you want to disable sensors defined in the base YAML, one trick is to wrap them in conditional blocks (e.g., ${enable_temperature}) inside your base package and let users override with substitutions.
